name: wordpressreleaser

on:
  pull_request:
  push:
    tags:
      - "*"

jobs:
  wordpressreleaser:
    name: Deploy to WP.org
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print Release Version
        run: echo Release version is ${{ github.ref_name }}

      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: hls-player

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ steps.deploy.outputs.zip-path }}
          name: hls-player-v${{ github.ref_name }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
